### ISSUE TITLE
Any issues with Astronomy v1?

### ISSUE THREAD

**Issue by luzlab** [rclai/meteor-astronomy-simple-schema#1]
I got the following error trying to install and noticed this project has had an update in a couple of years. Is this still mostly working? I'll give it a try but would be nice to know the devs are still active.

```
While selecting package versions:
error: Potentially incompatible change required to top-level dependency: jagi:astronomy 1.2.11, was 2.4.3.
Constraints on package "jagi:astronomy":
* jagi:astronomy@1.0.0 <- lai:astronomy-simple-schema 0.0.2
* jagi:astronomy@1.0.2 <- jagi:astronomy-validators 1.0.3 <- lai:astronomy-simple-schema 0.0.2
```

**Comment by lukejagodzinski** [comment]
From what I see this package was designed to work with Astronomy v1 and you're using v2 so it won't work. And updating this package will be probably hard to do as Astronomy v2 has a lot of API changes and new features.

**Comment by rclai** [comment]
Oh yeah, I was working on this package a long time ago, but haven't picked it up since. Sorry.
